### ISSUE TITLE
I am getting an undefined value in  while fetching the data

### ISSUE THREAD

**Issue by tanbiralam** [ShariqAnsari88/strapi-simple-one-client#1]
Whenever I clicked a product from the home page or category page it redirects me to a single page but the product id is undefined showing in the URL http://localhost:3000/product/undefined. Please help me to fix this issues.

http://localhost:1337/api/products?populate=*&filters[id][$ne]=undefined&filters[categories][id]=undefined&pagination[start]=0&pagination[limit]=4

{
  "data": [],
  "meta": {
    "pagination": {
      "start": 0,
      "limit": 4,
      "total": 0
    }
  }
}

this is showing.

**Comment by shivgan** [comment]
sorry i am also not used to it vey much
